<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
    <Nullable>annotations</Nullable>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>disable</ImplicitUsings>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="coverlet.collector">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="xunit.runner.visualstudio">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="xunit.v3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\ActDim.Practix.Abstractions\ActDim.Practix.Abstractions.csproj" />
		<ProjectReference Include="..\..\ActDim.Practix.Common\ActDim.Practix.Common.csproj" />
		<ProjectReference Include="..\..\ActDim.Practix.Json\ActDim.Practix.Json.csproj" />
	</ItemGroup>

</Project>
